# Generated by Django 4.2.16 on 2024-11-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_product_order_items_remove_order_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
