# Generated by Django 4.2.16 on 2024-11-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_rename_customer_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
